import 'dart:convert';
import 'dart:typed_data';
import 'dart:io';
import 'package:image_picker/image_picker.dart';
import '../models/client.dart';
import '../services/api_service.dart';
import '../services/database_helper.dart';
import '../services/auth_service.dart';

class ClientService {
  final ApiService _apiService = ApiService();
  final DatabaseHelper _databaseHelper = DatabaseHelper();
  final AuthService _authService = AuthService();

  // Singleton pattern
  static final ClientService _instance = ClientService._internal();
  factory ClientService() => _instance;
  ClientService._internal();

  /// Add a new client locally and queue for sync
  Future<Map<String, dynamic>> addClient({
    required String firstName,
    required String lastName,
    required String nationalIdNumber,
    required String gender,
    required String nextOfKinContact,
    required String nextOfKinName,
    required String relationshipWithNOK,
    required String whatsAppContact,
    required String emailAddress,
    Uint8List? photoBytes,
    String? photoExtension,
  }) async {
    try {
      final currentUser = _authService.currentUser;
      if (currentUser == null) {
        throw Exception('User not authenticated');
      }

      // Generate a temporary client ID for queued client
      final tempClientId = 'TEMP_${DateTime.now().millisecondsSinceEpoch}';

      // Prepare client data for local storage
      final clientData = {
        'clientId': tempClientId,
        'branchId': currentUser.branchId,
        'firstName': firstName,
        'lastName': lastName,
        'fullName': '$firstName $lastName',
        'branch': currentUser.branch,
        'whatsAppContact': whatsAppContact,
        'emailAddress': emailAddress,
        'nationalIdNumber': nationalIdNumber,
        'capturedBy': currentUser.fullName,
        'gender': gender,
        'nextOfKinContact': nextOfKinContact,
        'nextOfKinName': nextOfKinName,
        'relationshipWithNOK': relationshipWithNOK,
        'pin': null, // Will be generated by server
        'photo': photoBytes != null ? base64Encode(photoBytes) : null,
        'photoBytes': photoBytes,
        'photoExtension': photoExtension,
        'syncStatus': 'queued',
      };

      // Save to local database
      await _databaseHelper.insertQueuedClient(clientData);

      // Attempt immediate sync
      final syncResult = await _attemptClientSync(tempClientId);

      return {
        'success': true,
        'message': syncResult['success']
            ? 'Client added and synced successfully'
            : 'Client saved locally. Will sync when online.',
        'clientId': tempClientId,
        'synced': syncResult['success'],
        'syncedClientId': syncResult['clientId'],
      };
    } catch (e) {
      print('Error adding client: $e');
      return {'success': false, 'message': 'Failed to add client: $e'};
    }
  }

  /// Attempt to sync a single queued client
  Future<Map<String, dynamic>> _attemptClientSync(String tempClientId) async {
    try {
      final queuedClients = await _databaseHelper.getQueuedClients();
      final clientData = queuedClients.firstWhere(
        (client) => client['clientId'] == tempClientId,
        orElse: () => <String, dynamic>{},
      );

      if (clientData.isEmpty) {
        return {'success': false, 'message': 'Client not found'};
      }

      // Prepare API call
      Uint8List? photoBytes;
      String? photoExtension;

      if (clientData['photoBytes'] != null) {
        photoBytes = clientData['photoBytes'] as Uint8List;
        photoExtension = clientData['photoExtension'] as String?;
      }

      final response = await _apiService.addClientWithFile(
        firstName: clientData['firstName'],
        lastName: clientData['lastName'],
        nationalIdNumber: clientData['nationalIdNumber'],
        gender: clientData['gender'],
        nextOfKinContact: clientData['nextOfKinContact'],
        nextOfKinName: clientData['nextOfKinName'],
        relationshipWithNOK: clientData['relationshipWithNOK'],
        whatsAppContact: clientData['whatsAppContact'],
        emailAddress: clientData['emailAddress'],
        branch: clientData['branch'],
        photoBytes: photoBytes,
        photoExtension: photoExtension,
      );

      if (response.statusCode == 200) {
        final responseData = json.decode(response.body);
        
        // Check if the response contains an error message despite 200 status
        if (responseData.containsKey('message') && 
            responseData['message'].toString().contains('successfully') &&
            responseData.containsKey('clientId')) {
          
          final syncedClientId = responseData['clientId'].toString();
          
          try {
            // Move from queued to synced
            await _databaseHelper.moveQueuedClientToSynced(
              tempClientId,
              syncedClientId,
            );
            
            return {
              'success': true,
              'message': responseData['message'],
              'clientId': syncedClientId,
            };
          } catch (dbError) {
            print('Database error while syncing: $dbError');
            // Just delete the queued client since API call was successful
            await _databaseHelper.deleteQueuedClient(tempClientId);
            return {
              'success': true,
              'message': 'Client synced successfully (database updated)',
              'clientId': syncedClientId,
            };
          }
        } else {
          // API returned 200 but with error content
          final errorMessage = responseData['message'] ?? 'Sync failed';
          await _databaseHelper.updateQueuedClientSyncAttempt(
            tempClientId,
            errorMessage,
          );
          return {'success': false, 'message': errorMessage};
        }
      } else {
        // Update sync attempt
        final errorMessage =
            response.statusCode == 400 && response.body.isNotEmpty
            ? json.decode(response.body)['message'] ?? 'Sync failed'
            : 'Server error: ${response.statusCode}';

        await _databaseHelper.updateQueuedClientSyncAttempt(
          tempClientId,
          errorMessage,
        );

        return {'success': false, 'message': errorMessage};
      }
    } catch (e) {
      print('Client sync error: $e');
      await _databaseHelper.updateQueuedClientSyncAttempt(
        tempClientId,
        e.toString(),
      );

      return {'success': false, 'message': 'Sync failed: $e'};
    }
  }

  /// Upload photo for an existing client
  Future<Map<String, dynamic>> uploadClientPhoto({
    required String clientId,
    required Uint8List photoBytes,
    required String photoExtension,
  }) async {
    try {
      final response = await _apiService.uploadClientPhoto(
        clientId: clientId,
        photoBytes: photoBytes,
        photoExtension: photoExtension,
      );

      if (response.statusCode == 200) {
        final responseData = json.decode(response.body);

        // Update local client with photo URL
        final client = await _databaseHelper.getClientById(clientId);
        if (client != null) {
          final updatedClient = client.copyWith(
            photo: responseData['photoUrl'],
          );
          await _databaseHelper.updateClient(updatedClient);
        }

        return {
          'success': true,
          'message': responseData['message'],
          'photoUrl': responseData['photoUrl'],
        };
      } else {
        final errorMessage =
            response.statusCode == 400 && response.body.isNotEmpty
            ? json.decode(response.body)['message'] ?? 'Upload failed'
            : 'Server error: ${response.statusCode}';

        return {'success': false, 'message': errorMessage};
      }
    } catch (e) {
      print('Photo upload error: $e');
      return {'success': false, 'message': 'Upload failed: $e'};
    }
  }

  /// Get client photo URL
  Future<String?> getClientPhotoUrl(String clientId) async {
    try {
      final response = await _apiService.getClientPhotoUrl(clientId);

      if (response.statusCode == 200) {
        // The response should be just the URL as a string
        return response.body.trim().replaceAll('"', ''); // Remove any quotes
      } else {
        print('Failed to get photo URL: ${response.statusCode}');
        return null;
      }
    } catch (e) {
      print('Error getting photo URL: $e');
      return null;
    }
  }

  /// Pick image from gallery
  Future<Map<String, dynamic>?> pickImageFromGallery() async {
    try {
      final ImagePicker picker = ImagePicker();
      final XFile? image = await picker.pickImage(
        source: ImageSource.gallery,
        maxWidth: 1024,
        maxHeight: 1024,
        imageQuality: 80,
      );

      if (image != null) {
        final bytes = await image.readAsBytes();
        final extension = image.path.split('.').last.toLowerCase();

        if (!['jpg', 'jpeg', 'png'].contains(extension)) {
          throw Exception('Only JPG and PNG images are supported');
        }

        return {'bytes': bytes, 'extension': extension, 'path': image.path};
      }

      return null;
    } catch (e) {
      print('Error picking image: $e');
      throw e;
    }
  }

  /// Get all queued clients
  Future<List<Map<String, dynamic>>> getQueuedClients() async {
    return await _databaseHelper.getQueuedClientsByStatus('queued');
  }

  /// Get all synced clients
  Future<List<Client>> getSyncedClients() async {
    return await _databaseHelper.getAllClients();
  }

  /// Delete queued client after confirmation
  Future<bool> deleteQueuedClient(String clientId) async {
    try {
      final result = await _databaseHelper.deleteQueuedClient(clientId);
      return result > 0;
    } catch (e) {
      print('Error deleting queued client: $e');
      return false;
    }
  }

  /// Auto-sync all queued clients (background service)
  Future<void> autoSyncQueuedClients() async {
    try {
      final queuedClients = await _databaseHelper.getQueuedClientsByStatus(
        'queued',
      );

      for (final clientData in queuedClients) {
        final clientId = clientData['clientId'] as String;
        final syncAttempts = clientData['syncAttempts'] as int? ?? 0;

        // Skip if too many attempts (max 3)
        if (syncAttempts >= 3) continue;

        // Skip if recently attempted (wait at least 5 minutes)
        final lastAttempt = clientData['lastSyncAttempt'] as int?;
        if (lastAttempt != null) {
          final timeSinceLastAttempt =
              DateTime.now().millisecondsSinceEpoch - lastAttempt;
          if (timeSinceLastAttempt < 300000) continue; // 5 minutes
        }

        await _attemptClientSync(clientId);

        // Small delay between sync attempts
        await Future.delayed(const Duration(seconds: 2));
      }
    } catch (e) {
      print('Auto-sync error: $e');
    }
  }

  /// Clean up old synced clients (older than 24 hours)
  Future<void> cleanupOldSyncedClients() async {
    try {
      final deletedCount = await _databaseHelper
          .deleteSyncedClientsOlderThan24Hours();
      print('Cleaned up $deletedCount old synced clients');
    } catch (e) {
      print('Error during cleanup: $e');
    }
  }

  /// Format phone number with Zimbabwe prefix
  String formatPhoneNumber(String phoneInput) {
    // Remove any non-digit characters
    String digitsOnly = phoneInput.replaceAll(RegExp(r'\D'), '');

    // If already starts with 263, return with +
    if (digitsOnly.startsWith('263')) {
      return '+$digitsOnly';
    }

    // If starts with 7, add 263 prefix
    if (digitsOnly.startsWith('7') && digitsOnly.length >= 9) {
      return '+263${digitsOnly.substring(1)}';
    }

    // If starts with 0, replace with 263
    if (digitsOnly.startsWith('0') && digitsOnly.length >= 10) {
      return '+263${digitsOnly.substring(1)}';
    }

    // Default: assume it's a local number and add full prefix
    return '+2637$digitsOnly';
  }

  /// Validate phone number format
  bool isValidPhoneNumber(String phone) {
    final cleanPhone = phone.replaceAll(RegExp(r'\D'), '');

    // Should be Zimbabwe format: +263 followed by 9 digits
    if (phone.startsWith('+2637') && cleanPhone.length == 12) {
      return true;
    }

    return false;
  }
}
